/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app.templates'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppExecutionsRouteImport } from './routes/_authenticated/app.executions'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppCrmIndexRouteImport } from './routes/_authenticated/app.crm.index'
import { Route as AuthenticatedAppCrmPipelineRouteImport } from './routes/_authenticated/app.crm.pipeline'
import { Route as AuthenticatedAppAgentsNewRouteImport } from './routes/_authenticated/app.agents.new'
import { Route as AuthenticatedAppAgentsAgentIdRouteImport } from './routes/_authenticated/app.agents.$agentId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/app/templates',
    path: '/app/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppExecutionsRoute =
  AuthenticatedAppExecutionsRouteImport.update({
    id: '/app/executions',
    path: '/app/executions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCrmIndexRoute =
  AuthenticatedAppCrmIndexRouteImport.update({
    id: '/app/crm/',
    path: '/app/crm/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCrmPipelineRoute =
  AuthenticatedAppCrmPipelineRouteImport.update({
    id: '/app/crm/pipeline',
    path: '/app/crm/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAgentsNewRoute =
  AuthenticatedAppAgentsNewRouteImport.update({
    id: '/app/agents/new',
    path: '/app/agents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAgentsAgentIdRoute =
  AuthenticatedAppAgentsAgentIdRouteImport.update({
    id: '/app/agents/$agentId',
    path: '/app/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/executions': typeof AuthenticatedAppExecutionsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/app/agents/new': typeof AuthenticatedAppAgentsNewRoute
  '/app/crm/pipeline': typeof AuthenticatedAppCrmPipelineRoute
  '/app/crm/': typeof AuthenticatedAppCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/executions': typeof AuthenticatedAppExecutionsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/app/agents/new': typeof AuthenticatedAppAgentsNewRoute
  '/app/crm/pipeline': typeof AuthenticatedAppCrmPipelineRoute
  '/app/crm': typeof AuthenticatedAppCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/executions': typeof AuthenticatedAppExecutionsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/agents/$agentId': typeof AuthenticatedAppAgentsAgentIdRoute
  '/_authenticated/app/agents/new': typeof AuthenticatedAppAgentsNewRoute
  '/_authenticated/app/crm/pipeline': typeof AuthenticatedAppCrmPipelineRoute
  '/_authenticated/app/crm/': typeof AuthenticatedAppCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/invite/$token'
    | '/app/audit'
    | '/app/executions'
    | '/app/settings'
    | '/app/team'
    | '/app/templates'
    | '/app/'
    | '/app/agents/$agentId'
    | '/app/agents/new'
    | '/app/crm/pipeline'
    | '/app/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/invite/$token'
    | '/app/audit'
    | '/app/executions'
    | '/app/settings'
    | '/app/team'
    | '/app/templates'
    | '/app'
    | '/app/agents/$agentId'
    | '/app/agents/new'
    | '/app/crm/pipeline'
    | '/app/crm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/invite/$token'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/executions'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/'
    | '/_authenticated/app/agents/$agentId'
    | '/_authenticated/app/agents/new'
    | '/_authenticated/app/crm/pipeline'
    | '/_authenticated/app/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/app/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/executions': {
      id: '/_authenticated/app/executions'
      path: '/app/executions'
      fullPath: '/app/executions'
      preLoaderRoute: typeof AuthenticatedAppExecutionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/crm/': {
      id: '/_authenticated/app/crm/'
      path: '/app/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AuthenticatedAppCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/crm/pipeline': {
      id: '/_authenticated/app/crm/pipeline'
      path: '/app/crm/pipeline'
      fullPath: '/app/crm/pipeline'
      preLoaderRoute: typeof AuthenticatedAppCrmPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agents/new': {
      id: '/_authenticated/app/agents/new'
      path: '/app/agents/new'
      fullPath: '/app/agents/new'
      preLoaderRoute: typeof AuthenticatedAppAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agents/$agentId': {
      id: '/_authenticated/app/agents/$agentId'
      path: '/app/agents/$agentId'
      fullPath: '/app/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAppAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppExecutionsRoute: typeof AuthenticatedAppExecutionsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAgentsAgentIdRoute: typeof AuthenticatedAppAgentsAgentIdRoute
  AuthenticatedAppAgentsNewRoute: typeof AuthenticatedAppAgentsNewRoute
  AuthenticatedAppCrmPipelineRoute: typeof AuthenticatedAppCrmPipelineRoute
  AuthenticatedAppCrmIndexRoute: typeof AuthenticatedAppCrmIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppExecutionsRoute: AuthenticatedAppExecutionsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAgentsAgentIdRoute: AuthenticatedAppAgentsAgentIdRoute,
  AuthenticatedAppAgentsNewRoute: AuthenticatedAppAgentsNewRoute,
  AuthenticatedAppCrmPipelineRoute: AuthenticatedAppCrmPipelineRoute,
  AuthenticatedAppCrmIndexRoute: AuthenticatedAppCrmIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
